//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceClientProduct {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceClientProduct.IServiceProduct")]
    public interface IServiceProduct {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/GetProducts", ReplyAction="http://tempuri.org/IServiceProduct/GetProductsResponse")]
        Data.Urunler[] GetProducts(int SupplierId, string Role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/GetProducts", ReplyAction="http://tempuri.org/IServiceProduct/GetProductsResponse")]
        System.Threading.Tasks.Task<Data.Urunler[]> GetProductsAsync(int SupplierId, string Role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/GetProductsWin", ReplyAction="http://tempuri.org/IServiceProduct/GetProductsWinResponse")]
        Data.Urunler[] GetProductsWin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/GetProductsWin", ReplyAction="http://tempuri.org/IServiceProduct/GetProductsWinResponse")]
        System.Threading.Tasks.Task<Data.Urunler[]> GetProductsWinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/DeleteProducts", ReplyAction="http://tempuri.org/IServiceProduct/DeleteProductsResponse")]
        void DeleteProducts(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/DeleteProducts", ReplyAction="http://tempuri.org/IServiceProduct/DeleteProductsResponse")]
        System.Threading.Tasks.Task DeleteProductsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/UpdatePriceANDName", ReplyAction="http://tempuri.org/IServiceProduct/UpdatePriceANDNameResponse")]
        void UpdatePriceANDName(int id, decimal fiyat, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/UpdatePriceANDName", ReplyAction="http://tempuri.org/IServiceProduct/UpdatePriceANDNameResponse")]
        System.Threading.Tasks.Task UpdatePriceANDNameAsync(int id, decimal fiyat, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/FindProducts", ReplyAction="http://tempuri.org/IServiceProduct/FindProductsResponse")]
        Data.Urunler FindProducts(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/FindProducts", ReplyAction="http://tempuri.org/IServiceProduct/FindProductsResponse")]
        System.Threading.Tasks.Task<Data.Urunler> FindProductsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/Login", ReplyAction="http://tempuri.org/IServiceProduct/LoginResponse")]
        Data.UserDTO Login(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/Login", ReplyAction="http://tempuri.org/IServiceProduct/LoginResponse")]
        System.Threading.Tasks.Task<Data.UserDTO> LoginAsync(string Email, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceProductChannel : Client.ServiceClientProduct.IServiceProduct, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProductClient : System.ServiceModel.ClientBase<Client.ServiceClientProduct.IServiceProduct>, Client.ServiceClientProduct.IServiceProduct {
        
        public ServiceProductClient() {
        }
        
        public ServiceProductClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceProductClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Data.Urunler[] GetProducts(int SupplierId, string Role) {
            return base.Channel.GetProducts(SupplierId, Role);
        }
        
        public System.Threading.Tasks.Task<Data.Urunler[]> GetProductsAsync(int SupplierId, string Role) {
            return base.Channel.GetProductsAsync(SupplierId, Role);
        }
        
        public Data.Urunler[] GetProductsWin() {
            return base.Channel.GetProductsWin();
        }
        
        public System.Threading.Tasks.Task<Data.Urunler[]> GetProductsWinAsync() {
            return base.Channel.GetProductsWinAsync();
        }
        
        public void DeleteProducts(int id) {
            base.Channel.DeleteProducts(id);
        }
        
        public System.Threading.Tasks.Task DeleteProductsAsync(int id) {
            return base.Channel.DeleteProductsAsync(id);
        }
        
        public void UpdatePriceANDName(int id, decimal fiyat, string name) {
            base.Channel.UpdatePriceANDName(id, fiyat, name);
        }
        
        public System.Threading.Tasks.Task UpdatePriceANDNameAsync(int id, decimal fiyat, string name) {
            return base.Channel.UpdatePriceANDNameAsync(id, fiyat, name);
        }
        
        public Data.Urunler FindProducts(int id) {
            return base.Channel.FindProducts(id);
        }
        
        public System.Threading.Tasks.Task<Data.Urunler> FindProductsAsync(int id) {
            return base.Channel.FindProductsAsync(id);
        }
        
        public Data.UserDTO Login(string Email, string Password) {
            return base.Channel.Login(Email, Password);
        }
        
        public System.Threading.Tasks.Task<Data.UserDTO> LoginAsync(string Email, string Password) {
            return base.Channel.LoginAsync(Email, Password);
        }
    }
}
